### ISSUE TITLE
Make Docker registry configurable

### ISSUE THREAD

**Issue by berendt** [optiopay/klar#9] opened 2017-01-05 12:44 UTC
At the moment the used Docker registry is hardcoded (``const dockerHub = "registry-1.docker.io"``). The Docker registry should be configurable to be able to use a private Docker registry.

**Comment by berendt** [comment] 2017-01-08 14:15
Ah cool, thanks for the fast reply. I will test this tomorrow.

**Comment by berendt** [comment] 2017-01-09 07:31
I tried to scan an image on a private password protected registry:

```
CLAIR_ADDR=clair DOCKER_USER=xxx DOCKER_PASSWORD=xxx klar registry.xzy/infrastructure/jenkins:1.2.3
```

This failed with the following error message on Clair:

```
2017-01-09 07:22:00.123609 W | detectors: could not download layer: got status code 401, expected 2XX
2017-01-09 07:22:00.123708 E | worker: layer sha256:75a822cd7888e394c49828b951061402d31745f596b1f502758570f2d0ee79e2: failed to extract data from https://registry.xzy/v2/infrastructure/jenkins/blobs/sha256:75a822cd7888e394c49828b951061402d31745f596b1f502758570f2d0ee79e2: could not find layer
```

A manual download of the failed layer with the username/password is working like expected.

**Comment by berendt** [comment] 2017-01-18 12:27
@hashmap Any news here?

**Comment by supereagle** [comment] 2017-01-19 01:42
Have checked the code, there is no error to pass the registry credentials. At the same time, have tested several times, not reproduce this error. @hashmap Any clues?

**Comment by hashmap** [comment] 2017-01-20 08:58
@berendt I assume you have a password-protected web server in front of your private registry, am I right? In this case you need support of HTTP basic auth (for example) in addition to registry auth dance. It looks like valuable feature.

**Comment by berendt** [comment] 2017-01-21 22:25
@hashmap I am using Nexus OSS as private Docker registry. I am not sure if it requires an additional HTTP authentication. I can directly login to the registry with the ``docker login`` command.

**Comment by supereagle** [comment] 2017-03-23 23:25
Maybe this issue is the same as #12, has been fixed by PR #14

**Comment by supereagle** [comment] 2017-03-24 14:52
@berendt  You can have a try on the latest release [v1.2.1](https://github.com/optiopay/klar/releases/tag/v1.2.1). If this error still exists, please report to us. Thanks.

**Comment by hashmap** [comment] 2017-04-19 12:56
@berendt I'm closing this issue, feel free to reopen it if problem still exists

**Closed by hashmap** 2017-04-19 12:56 UTC
